import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "primary":                   "#2b6954",
        "primary-container":         "#71af97",
        "primary-fixed":             "#b0f0d6",
        "primary-fixed-dim":         "#95d3ba",
        "on-primary":                "#ffffff",
        "on-primary-container":      "#004231",
        "on-primary-fixed":          "#002117",
        "on-primary-fixed-variant":  "#0b513d",
        "secondary":                 "#515f74",
        "secondary-container":       "#d5e3fc",
        "secondary-fixed":           "#d5e3fc",
        "secondary-fixed-dim":       "#b9c7df",
        "on-secondary":              "#ffffff",
        "on-secondary-container":    "#57657a",
        "on-secondary-fixed":        "#0d1c2e",
        "on-secondary-fixed-variant":"#3a485b",
        "tertiary":                  "#006b5f",
        "tertiary-container":        "#0db6a4",
        "tertiary-fixed":            "#71f8e4",
        "tertiary-fixed-dim":        "#4fdbc8",
        "on-tertiary":               "#ffffff",
        "on-tertiary-container":     "#004139",
        "on-tertiary-fixed":         "#00201c",
        "on-tertiary-fixed-variant": "#005048",
        "error":                     "#ba1a1a",
        "error-container":           "#ffdad6",
        "on-error":                  "#ffffff",
        "on-error-container":        "#93000a",
        "surface":                   "#faf9f6",
        "surface-bright":            "#faf9f6",
        "surface-dim":               "#dbdad7",
        "surface-variant":           "#e3e2e0",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f4f3f1",
        "surface-container":         "#efeeeb",
        "surface-container-high":    "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-surface":                "#1a1c1a",
        "on-surface-variant":        "#3c4a42",
        "inverse-surface":           "#2f312f",
        "inverse-on-surface":        "#f2f1ee",
        "inverse-primary":           "#95d3ba",
        "surface-tint":              "#2b6954",
        "outline":                   "#6c7a71",
        "outline-variant":           "#bbcabf",
        "background":                "#faf9f6",
        "on-background":             "#1a1c1a",
      },
      fontFamily: {
        headline: ['"Nunito Sans"', 'sans-serif'],
        body:     ['"Montserrat"', 'sans-serif'],
        label:    ['"Montserrat"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config
